#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
client:
 tls:
  enabled: true

 security:
  enabled: true
  hashAlgorithm: "SHA2"
  level: 256

 tcert:
  batch:
    size: 200

 logging:
  level: info

 keystore:
  path: /tmp/msp

 cryptoconfig:
  path: "$GOPATH/src/github.com/C0rwin/pgdays/artifacts/crypto-config"

# network provides a static definition of a Hyperledger Fabric network
 network:
  # list of ordering service nodes
  orderers:
   # orderer name
   orderer0:
    host: "localhost"
    port: 7050
    tls:
     # Certificate location absolute path
     certificate: "$GOPATH/src/github.com/C0rwin/pgdays/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/cacerts/ca.example.com-cert.pem"
     # For testing only: overrides the virtual host name of the authority
     serverHostOverride: "orderer.example.com"
  # ap of member organizations forming the network
  organizations:
    # Org1 name
    org1:
      # Membership Service Provider ID for this organization
      mspID: "Org1MSP"
      # Peers that are part of this organization
      peers:
       # Peer name
       peer0:
        host: "localhost"
        port: 7051
        eventHost: "localhost"
        eventPort: 7053
        primary: true
        tls:
         # Certificate location absolute path
         certificate: "$GOPATH/src/github.com/C0rwin/pgdays/artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/cacerts/ca.org1.example.com-cert.pem"
         serverHostOverride: "peer0.org1.example.com"
